version: '1'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=12345
    restart: always

  shrinker:
    image: azatsepin/shrinker:latest
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - PREFIX=http://shrink.ua/
      - SERVER_PORT=80
    links:
      - db
    ports:
      - "80:80"